import '#styles/globals.css'
import type { Metadata } from 'next'
import type { Children } from '#interfaces/children'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<Children>) {
	return (
		<html lang="en">
			<body className="antialiased">{children}</body>
		</html>
	)
}
